package AVL_Tree;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Mathys
 */
public class GUIFrame extends javax.swing.JFrame {

      DefaultTableModel tabelModel, tabelMode2, tabelMode3, tabelMode4;
      TableColumnModel columnModel, columnMode2, columnMode3, columnMode4;
      datPohon dPohon = new datPohon();

      /**
       * Creates new form GUIFrame
       */
      public GUIFrame() {
	    initComponents();
	    dPohon.fillData();
	    tampilLists();
      }

      /**
       * This method is called from within the constructor to initialize the
       * form. WARNING: Do NOT modify this code. The content of this method is
       * always regenerated by the Form Editor.
       */
      @SuppressWarnings("unchecked")
      // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
      private void initComponents() {

            jPanel1 = new javax.swing.JPanel();
            jTabbedPane1 = new javax.swing.JTabbedPane();
            tabManipulasi = new javax.swing.JPanel();
            jPanel2 = new javax.swing.JPanel();
            labelTambah = new javax.swing.JLabel();
            fieldTambah = new javax.swing.JTextField();
            labelHapus = new javax.swing.JLabel();
            fieldHapus = new javax.swing.JTextField();
            labelCari = new javax.swing.JLabel();
            fieldCari = new javax.swing.JTextField();
            btnTambah = new javax.swing.JButton();
            btnHapus = new javax.swing.JButton();
            btnCari = new javax.swing.JButton();
            jScrollPane1 = new javax.swing.JScrollPane();
            jTable1 = new javax.swing.JTable();
            tabInor = new javax.swing.JPanel();
            jScrollPane2 = new javax.swing.JScrollPane();
            jTable2 = new javax.swing.JTable();
            jPanel3 = new javax.swing.JPanel();
            jScrollPane3 = new javax.swing.JScrollPane();
            jTable3 = new javax.swing.JTable();
            jPanel4 = new javax.swing.JPanel();
            jScrollPane4 = new javax.swing.JScrollPane();
            jTable4 = new javax.swing.JTable();

            setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

            jTabbedPane1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

            jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            labelTambah.setText("Tambah Data");

            fieldTambah.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        fieldTambahActionPerformed(evt);
                  }
            });
            fieldTambah.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyPressed(java.awt.event.KeyEvent evt) {
                        fieldTambahKeyPressed(evt);
                  }
            });

            labelHapus.setText("Hapus Data");

            fieldHapus.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        fieldHapusActionPerformed(evt);
                  }
            });
            fieldHapus.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyPressed(java.awt.event.KeyEvent evt) {
                        fieldHapusKeyPressed(evt);
                  }
            });

            labelCari.setText("Cari Data");

            fieldCari.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        fieldCariActionPerformed(evt);
                  }
            });
            fieldCari.addKeyListener(new java.awt.event.KeyAdapter() {
                  public void keyPressed(java.awt.event.KeyEvent evt) {
                        fieldCariKeyPressed(evt);
                  }
            });

            btnTambah.setText("OK");
            btnTambah.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnTambahActionPerformed(evt);
                  }
            });

            btnHapus.setText("OK");
            btnHapus.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnHapusActionPerformed(evt);
                  }
            });

            btnCari.setText("OK");
            btnCari.addActionListener(new java.awt.event.ActionListener() {
                  public void actionPerformed(java.awt.event.ActionEvent evt) {
                        btnCariActionPerformed(evt);
                  }
            });

            javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
            jPanel2.setLayout(jPanel2Layout);
            jPanel2Layout.setHorizontalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                              .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(labelTambah)
                                          .addComponent(labelHapus)
                                          .addComponent(labelCari))
                                    .addGap(0, 0, Short.MAX_VALUE))
                              .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                          .addComponent(fieldCari, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                                          .addComponent(fieldHapus, javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(fieldTambah))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                          .addComponent(btnTambah)
                                          .addComponent(btnHapus)
                                          .addComponent(btnCari, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addContainerGap())
            );
            jPanel2Layout.setVerticalGroup(
                  jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(labelTambah)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(fieldTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(btnTambah))
                        .addGap(18, 18, 18)
                        .addComponent(labelHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(fieldHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(btnHapus))
                        .addGap(18, 18, 18)
                        .addComponent(labelCari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(fieldCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addComponent(btnCari))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            );

            jScrollPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            jTable1.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                  }
            ));
            jScrollPane1.setViewportView(jTable1);

            javax.swing.GroupLayout tabManipulasiLayout = new javax.swing.GroupLayout(tabManipulasi);
            tabManipulasi.setLayout(tabManipulasiLayout);
            tabManipulasiLayout.setHorizontalGroup(
                  tabManipulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(tabManipulasiLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 460, Short.MAX_VALUE))
            );
            tabManipulasiLayout.setVerticalGroup(
                  tabManipulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 441, Short.MAX_VALUE)
            );

            jTabbedPane1.addTab("Manipulasi Data", tabManipulasi);

            jScrollPane2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            jTable2.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                  }
            ));
            jScrollPane2.setViewportView(jTable2);

            javax.swing.GroupLayout tabInorLayout = new javax.swing.GroupLayout(tabInor);
            tabInor.setLayout(tabInorLayout);
            tabInorLayout.setHorizontalGroup(
                  tabInorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabInorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                        .addContainerGap())
            );
            tabInorLayout.setVerticalGroup(
                  tabInorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(tabInorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
            );

            jTabbedPane1.addTab("Inorder", tabInor);

            jScrollPane3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            jTable3.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                  }
            ));
            jScrollPane3.setViewportView(jTable3);

            javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
            jPanel3.setLayout(jPanel3Layout);
            jPanel3Layout.setHorizontalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanel3Layout.setVerticalGroup(
                  jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)
                        .addContainerGap())
            );

            jTabbedPane1.addTab("Preorder", jPanel3);

            jScrollPane4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

            jTable4.setModel(new javax.swing.table.DefaultTableModel(
                  new Object [][] {
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null},
                        {null, null, null, null}
                  },
                  new String [] {
                        "Title 1", "Title 2", "Title 3", "Title 4"
                  }
            ));
            jScrollPane4.setViewportView(jTable4);

            javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
            jPanel4.setLayout(jPanel4Layout);
            jPanel4Layout.setHorizontalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
                        .addContainerGap())
            );
            jPanel4Layout.setVerticalGroup(
                  jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane4)
                        .addContainerGap())
            );

            jTabbedPane1.addTab("Postorder", jPanel4);

            javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
            jPanel1.setLayout(jPanel1Layout);
            jPanel1Layout.setHorizontalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
            );
            jPanel1Layout.setVerticalGroup(
                  jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1)
                        .addContainerGap())
            );

            javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
            getContentPane().setLayout(layout);
            layout.setHorizontalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 808, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );
            layout.setVerticalGroup(
                  layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGap(0, 490, Short.MAX_VALUE)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                              .addGap(0, 0, Short.MAX_VALUE)
                              .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addGap(0, 0, Short.MAX_VALUE)))
            );

            pack();
      }// </editor-fold>//GEN-END:initComponents

        private void fieldTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTambahActionPerformed

        }//GEN-LAST:event_fieldTambahActionPerformed

        private void fieldHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHapusActionPerformed
	      // TODO add your handling code here:
        }//GEN-LAST:event_fieldHapusActionPerformed

      private void fieldCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCariActionPerformed
	    // TODO add your handling code here:
      }//GEN-LAST:event_fieldCariActionPerformed

      private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
	    String input = fieldTambah.getText();

	    if (!dPohon.getPohon().add(input)) {
		  JOptionPane.showMessageDialog(null,
			  "Gagal menambahkan " + input, "Warning",
			  JOptionPane.ERROR_MESSAGE);
		  clearField();
		  return;
	    }

	    refreshData();
	    JOptionPane.showMessageDialog(null,
		    input + " Berhasil ditambah", "Berhasil",
		    JOptionPane.INFORMATION_MESSAGE);
	    clearField();
      }//GEN-LAST:event_btnTambahActionPerformed

      private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
	    String input = fieldHapus.getText();

	    if (!dPohon.getPohon().remove(input)) {
		  JOptionPane.showMessageDialog(null,
			  input + " Tidak Ditemukan", "Gagal",
			  JOptionPane.ERROR_MESSAGE);
		  clearField();
		  return;
	    }

	    refreshData();
	    JOptionPane.showMessageDialog(null,
		    input + " Berhasil dihapus", "Berhasil",
		    JOptionPane.INFORMATION_MESSAGE);
	    clearField();
      }//GEN-LAST:event_btnHapusActionPerformed

      private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
	    String dicari = fieldCari.getText();

	    if (!dPohon.cari(dicari)) {
		  JOptionPane.showMessageDialog(null,
			  dicari + " Tidak Ditemukan", "Gagal",
			  JOptionPane.ERROR_MESSAGE);
		  clearField();
		  return;
	    }

	    refreshData();
	    JOptionPane.showMessageDialog(null,
		    String.format("%s di index ke %s\n", dicari, dPohon.getIndexBuku()),
		    "Ditemukan", JOptionPane.INFORMATION_MESSAGE);
	    clearField();
      }//GEN-LAST:event_btnCariActionPerformed

      private void fieldTambahKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldTambahKeyPressed
	    if (evt.getKeyCode() != java.awt.event.KeyEvent.VK_ENTER) {
		  return;
	    }

	    String input = fieldTambah.getText();

	    if (!dPohon.getPohon().add(input)) {
		  JOptionPane.showMessageDialog(null,
			  "Gagal menambahkan " + input, "Warning",
			  JOptionPane.ERROR_MESSAGE);
		  clearField();
		  return;
	    }

	    refreshData();
	    JOptionPane.showMessageDialog(null,
		    input + " Berhasil ditambah", "Berhasil",
		    JOptionPane.INFORMATION_MESSAGE);
	    clearField();
      }//GEN-LAST:event_fieldTambahKeyPressed

      private void fieldHapusKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldHapusKeyPressed
	    if (!(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER)) {
		  return;
	    }
	    String input = fieldHapus.getText();

	    if (!dPohon.getPohon().remove(input)) {
		  JOptionPane.showMessageDialog(null,
			  input + " Tidak Ditemukan", "Gagal",
			  JOptionPane.ERROR_MESSAGE);
		  clearField();
		  return;
	    }

	    refreshData();
	    JOptionPane.showMessageDialog(null,
		    input + " Berhasil dihapus", "Berhasil",
		    JOptionPane.INFORMATION_MESSAGE);
	    clearField();
      }//GEN-LAST:event_fieldHapusKeyPressed

      private void fieldCariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fieldCariKeyPressed
	    if (evt.getKeyCode() != java.awt.event.KeyEvent.VK_ENTER) {
		  return;
	    }
	    String dicari = fieldCari.getText();

	    if (!dPohon.cari(dicari)) {
		  JOptionPane.showMessageDialog(null,
			  dicari + " Tidak Ditemukan", "Gagal",
			  JOptionPane.ERROR_MESSAGE);
		  clearField();
		  return;
	    }

	    refreshData();
	    JOptionPane.showMessageDialog(null,
		    String.format("%s di index ke %s\n", dicari, dPohon.getIndexBuku()),
		    "Ditemukan", JOptionPane.INFORMATION_MESSAGE);
	    clearField();
      }//GEN-LAST:event_fieldCariKeyPressed

      public void tampilLists() {
	    tampilDataT1();
	    tampilDataT3();
	    tampilDataT4();
      }

      private void tampilDataT1() {
	    String[] kolom = {"No", "Judul"};
	    Object[][] objData = new Object[dPohon.getInorder().size()][1];
	    int i = 0;
	    for (String n : dPohon.getInorder()) {
		  String[] arrData = {String.valueOf(i + 1), n};
		  objData[i] = arrData;
		  i++;
	    }
	    tabelModel = new DefaultTableModel(objData, kolom) {
		  //membuat tabel tidak bisa diedit saat diklik
		  @Override
		  public boolean isCellEditable(int rowIndex, int colIndex) {
			return false;
		  }
	    };
	    jTable1.setModel(tabelModel);
	    columnModel = jTable1.getColumnModel();
	    columnModel.getColumn(0).setPreferredWidth(10);
	    columnModel.getColumn(1).setPreferredWidth(430);
	    jTable2.setModel(tabelModel);
	    columnMode2 = jTable2.getColumnModel();
	    columnMode2.getColumn(0).setPreferredWidth(10);
	    columnMode2.getColumn(1).setPreferredWidth(725);
      }

      private void tampilDataT3() {
	    String[] kolom = {"No", "Judul"};
	    Object[][] objData = new Object[dPohon.getPreorder().size()][2];
	    int i = 0;
	    for (String n : dPohon.getPreorder()) {
		  String[] arrData = {String.valueOf(i + 1), n};
		  objData[i] = arrData;
		  i++;
	    }
	    tabelMode2 = new DefaultTableModel(objData, kolom) {
		  //membuat tabel tidak bisa diedit saat diklik
		  @Override
		  public boolean isCellEditable(int rowIndex, int colIndex) {
			return false;
		  }
	    };
	    jTable3.setModel(tabelMode2);
	    columnMode3 = jTable3.getColumnModel();
	    columnMode3.getColumn(0).setPreferredWidth(10);
	    columnMode3.getColumn(1).setPreferredWidth(725);
      }

      private void tampilDataT4() {
	    String[] kolom = {"No", "Judul"};
	    Object[][] objData = new Object[dPohon.getPostorder().size()][1];
	    int i = 0;
	    for (String n : dPohon.getPostorder()) {
		  String[] arrData = {String.valueOf(i + 1), n};
		  objData[i] = arrData;
		  i++;
	    }
	    tabelMode3 = new DefaultTableModel(objData, kolom) {
		  //membuat tabel tidak bisa diedit saat diklik
		  @Override
		  public boolean isCellEditable(int rowIndex, int colIndex) {
			return false;
		  }
	    };
	    jTable4.setModel(tabelMode3);
	    columnMode4 = jTable4.getColumnModel();
	    columnMode4.getColumn(0).setPreferredWidth(10);
	    columnMode4.getColumn(1).setPreferredWidth(725);
      }

      private void clearField() {
	    fieldTambah.setText("");
	    fieldCari.setText("");
	    fieldHapus.setText("");
      }

      private void refreshData() {
	    dPohon.refreshData();
	    tampilLists();
      }

      /**
       * @param args the command line arguments
       */
      public static void main(String args[]) {
	    /* Set the Nimbus look and feel */
	    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	     */
	    try {
		  for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
			if ("Nimbus".equals(info.getName())) {
			      javax.swing.UIManager.setLookAndFeel(info.getClassName());
			      break;
			}
		  }
	    } catch (ClassNotFoundException ex) {
		  java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	    } catch (InstantiationException ex) {
		  java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	    } catch (IllegalAccessException ex) {
		  java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
		  java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	    }
	    //</editor-fold>
	    //</editor-fold>

	    /* Create and display the form */
	    GUIFrame frm = new GUIFrame();
	    frm.setTitle("Daftar Buku BST");
	    frm.setLocationRelativeTo(null);
	    java.awt.EventQueue.invokeLater(new Runnable() {
		  public void run() {
			frm.setVisible(true);
		  }
	    });
      }

      // Variables declaration - do not modify//GEN-BEGIN:variables
      private javax.swing.JButton btnCari;
      private javax.swing.JButton btnHapus;
      private javax.swing.JButton btnTambah;
      private javax.swing.JTextField fieldCari;
      private javax.swing.JTextField fieldHapus;
      private javax.swing.JTextField fieldTambah;
      private javax.swing.JPanel jPanel1;
      private javax.swing.JPanel jPanel2;
      private javax.swing.JPanel jPanel3;
      private javax.swing.JPanel jPanel4;
      private javax.swing.JScrollPane jScrollPane1;
      private javax.swing.JScrollPane jScrollPane2;
      private javax.swing.JScrollPane jScrollPane3;
      private javax.swing.JScrollPane jScrollPane4;
      private javax.swing.JTabbedPane jTabbedPane1;
      private javax.swing.JTable jTable1;
      private javax.swing.JTable jTable2;
      private javax.swing.JTable jTable3;
      private javax.swing.JTable jTable4;
      private javax.swing.JLabel labelCari;
      private javax.swing.JLabel labelHapus;
      private javax.swing.JLabel labelTambah;
      private javax.swing.JPanel tabInor;
      private javax.swing.JPanel tabManipulasi;
      // End of variables declaration//GEN-END:variables
}
